<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://www.map.es/xml-schemas"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    targetNamespace="http://www.map.es/xml-schemas"
    name="x53jiServicioOnlineIntermediacion">

    <wsdl:types>
        <xsd:schema targetNamespace="http://www.map.es/xml-schemas/respuesta">
            <xsd:import namespace="http://www.map.es/xml-schemas/respuesta" schemaLocation="respuesta.xsd"/>
        </xsd:schema>
        <xsd:schema targetNamespace="http://www.map.es/xml-schemas/peticion">
            <xsd:import namespace="http://www.map.es/xml-schemas/peticion" schemaLocation="peticion.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="peticionSincrona">
        <wsdl:part name="peticion" element="tns:Peticion"/>
    </wsdl:message>

    <wsdl:message name="peticionSincronaResponse">
        <wsdl:part name="respuesta" element="tns:Respuesta"/>
    </wsdl:message>

    <wsdl:portType name="IntermediacionOnlinePortType">
        <wsdl:operation name="peticionSincrona">
            <wsdl:input message="tns:peticionSincrona"/>
            <wsdl:output message="tns:peticionSincronaResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="IntermediacionOnlinePortBinding" type="tns:IntermediacionOnlinePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <wsdl:operation name="peticionSincrona">
            <soap:operation soapAction="peticionSincrona"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="x53jiServicioOnlineIntermediacion">
        <wsdl:port name="IntermediacionOnlinePort" binding="tns:IntermediacionOnlinePortBinding">
            <soap:address location="http://localhost:8080/ittxartela/online"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
